@echo off
setlocal enabledelayedexpansion
rem
rem Put `cauth` on the PATH on Windows.
rem
rem install.sh is the POSIX installer and cannot be reused here: it writes a bash
rem wrapper with a shebang, which Windows will not execute. This is the same shape,
rem a private venv plus a small launcher that execs it against the repo checkout,
rem expressed as the one script form that is present on a bare Windows box.
rem
rem uv is preferred over the system interpreter because the `python.exe` that ships
rem on PATH under WindowsApps is a 2 byte Microsoft Store stub that opens the Store
rem instead of running anything, and it shadows a real install depending on PATH order.
rem
rem Idempotent. Safe to re-run after a git pull.

set "REPO_DIR=%~dp0"
if "%REPO_DIR:~-1%"=="\" set "REPO_DIR=%REPO_DIR:~0,-1%"
if not defined CAUTH_VENV set "CAUTH_VENV=%USERPROFILE%\.local\share\claude-cauth\venv"
if not defined CAUTH_BIN set "CAUTH_BIN=%USERPROFILE%\.local\bin"
set "LAUNCHER=%CAUTH_BIN%\cauth.cmd"
set "VENV_PY=%CAUTH_VENV%\Scripts\python.exe"

echo   repo    %REPO_DIR%
echo   venv    %CAUTH_VENV%
echo   command %LAUNCHER%
echo.

rem ---------------------------------------------------------------------------- venv
set "UV="
for /f "delims=" %%I in ('where uv 2^>nul') do if not defined UV set "UV=%%I"
rem winget prints "restart your shell to use the new value" after it installs uv, and it
rem means it: the PATH edit does not reach a shell that is already open. Running this
rem script in that same shell is the common case, so look where winget puts its shims
rem before concluding there is no uv.
if not defined UV if exist "%LOCALAPPDATA%\Microsoft\WinGet\Links\uv.exe" set "UV=%LOCALAPPDATA%\Microsoft\WinGet\Links\uv.exe"

if exist "%VENV_PY%" (
  echo   venv already present, reusing it
) else (
  echo   creating venv
  if defined UV (
    "%UV%" venv "%CAUTH_VENV%" || goto :fail
  ) else (
    py -3 -m venv "%CAUTH_VENV%" 2>nul || python -m venv "%CAUTH_VENV%" || goto :novenv
  )
)
if not exist "%VENV_PY%" goto :novenv

echo   installing dependencies
if defined UV (
  "%UV%" pip install --python "%VENV_PY%" -r "%REPO_DIR%\requirements.txt" || goto :fail
) else (
  "%VENV_PY%" -m pip install --quiet --upgrade pip || goto :fail
  "%VENV_PY%" -m pip install --quiet -r "%REPO_DIR%\requirements.txt" || goto :fail
)

rem ---------------------------------------------------------------------------- launcher
if not exist "%CAUTH_BIN%" mkdir "%CAUTH_BIN%"
> "%LAUNCHER%" echo @echo off
>>"%LAUNCHER%" echo rem Generated by claude-cauth install.cmd. Re-run that script to regenerate.
>>"%LAUNCHER%" echo "%VENV_PY%" "%REPO_DIR%\cauth.py" %%*

rem ---------------------------------------------------------------------------- verify
echo.
rem --version, deliberately not `status`: status calls ensure_store, which would
rem CREATE an empty account index as a side effect of merely verifying the install.
rem On a fresh machine that empty index (mtime now) then wins any newer-file-wins
rem sync against a real index arriving from another machine. Verification is read only.
call "%LAUNCHER%" --version >nul 2>&1 || goto :unverified
echo   verified: cauth --version runs
"%VENV_PY%" -B -c "import sys; assert sys.version_info >= (3, 9), 'Python 3.9+ required'; sys.path.insert(0, sys.argv[1]); import tui, tokenui, tokenauth" "%REPO_DIR%" || goto :unverified
echo   verified: terminal UI imports
where claude >nul 2>&1 || echo   NEXT: install Claude Code before signing in. Run cauth doctor for details.

set "FOUND="
for /f "delims=" %%I in ('where cauth 2^>nul') do if not defined FOUND set "FOUND=%%I"
if /i "%FOUND%"=="%LAUNCHER%" (
  echo   verified: cauth resolves on PATH
) else (
  echo.
  echo   NOTE: this launcher is missing from PATH or shadowed by another cauth.
  echo   Put %CAUTH_BIN% first in your user PATH using Windows Environment Variables, then open a new terminal.
  echo   You can also run "%LAUNCHER%" directly.
)

echo.
echo   done. run: cauth
echo   Launch Claude with your selected token: cauth run
echo   PowerShell integration: cauth shell-init powershell ^| Out-String ^| Invoke-Expression
exit /b 0

:novenv
echo error: could not build a virtual environment. Install uv with 1>&2
echo   winget install --id=astral-sh.uv -e 1>&2
exit /b 1

:unverified
echo error: "%LAUNCHER%" --version did not run cleanly 1>&2
exit /b 1

:fail
echo error: install step failed, see the output above 1>&2
exit /b 1
